name: release-build

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  build-macos:
    name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          # # Apple Silicon
          - goos: darwin
            goarch: arm64
            runner: macos-14
          # # Intel macOS
          # - goos: darwin
          #   goarch: amd64
          #   runner: macos-14-intel

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build
        run: |
          scripts/build.sh .${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ktt_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/ktt.${{ matrix.goos }}-${{ matrix.goarch }}
